// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtKto76JrMLWWYmT2UdiQL-V2HYXjyWaE',
    appId: '1:891381154108:web:c49a8ad3c5e7f4c0589e39',
    messagingSenderId: '891381154108',
    projectId: 'apptarefas-aovivo',
    authDomain: 'apptarefas-aovivo.firebaseapp.com',
    storageBucket: 'apptarefas-aovivo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw6YT9XQHpaaIm3HV4UFnHVKAmIY4bDYE',
    appId: '1:891381154108:android:bb7478322b79bfaa589e39',
    messagingSenderId: '891381154108',
    projectId: 'apptarefas-aovivo',
    storageBucket: 'apptarefas-aovivo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXtJI3nTqDIM6JF9EV0f3m2MgFUJH0ftc',
    appId: '1:891381154108:ios:67d88cf118d57e59589e39',
    messagingSenderId: '891381154108',
    projectId: 'apptarefas-aovivo',
    storageBucket: 'apptarefas-aovivo.firebasestorage.app',
    iosBundleId: 'com.example.appTarefa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXtJI3nTqDIM6JF9EV0f3m2MgFUJH0ftc',
    appId: '1:891381154108:ios:67d88cf118d57e59589e39',
    messagingSenderId: '891381154108',
    projectId: 'apptarefas-aovivo',
    storageBucket: 'apptarefas-aovivo.firebasestorage.app',
    iosBundleId: 'com.example.appTarefa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtKto76JrMLWWYmT2UdiQL-V2HYXjyWaE',
    appId: '1:891381154108:web:8ae893384750e06e589e39',
    messagingSenderId: '891381154108',
    projectId: 'apptarefas-aovivo',
    authDomain: 'apptarefas-aovivo.firebaseapp.com',
    storageBucket: 'apptarefas-aovivo.firebasestorage.app',
  );

}