// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9HwcJvA5Njfv2yZchTIy0y_7iMGxSUZE',
    appId: '1:568202028804:web:4df333e96fa45bdebd5251',
    messagingSenderId: '568202028804',
    projectId: 'apptarefas-apresetar',
    authDomain: 'apptarefas-apresetar.firebaseapp.com',
    storageBucket: 'apptarefas-apresetar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATfDNVni0UychD00nmwoqQ9vUIPmoNTYc',
    appId: '1:568202028804:android:e0c27d9581548619bd5251',
    messagingSenderId: '568202028804',
    projectId: 'apptarefas-apresetar',
    storageBucket: 'apptarefas-apresetar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0yUuxP0rTtvqLcHUTJg8C-52dVLyTONg',
    appId: '1:568202028804:ios:98528eac55a71cdabd5251',
    messagingSenderId: '568202028804',
    projectId: 'apptarefas-apresetar',
    storageBucket: 'apptarefas-apresetar.firebasestorage.app',
    iosBundleId: 'com.example.appTarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0yUuxP0rTtvqLcHUTJg8C-52dVLyTONg',
    appId: '1:568202028804:ios:98528eac55a71cdabd5251',
    messagingSenderId: '568202028804',
    projectId: 'apptarefas-apresetar',
    storageBucket: 'apptarefas-apresetar.firebasestorage.app',
    iosBundleId: 'com.example.appTarefas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9HwcJvA5Njfv2yZchTIy0y_7iMGxSUZE',
    appId: '1:568202028804:web:85ceb2fd77e3e375bd5251',
    messagingSenderId: '568202028804',
    projectId: 'apptarefas-apresetar',
    authDomain: 'apptarefas-apresetar.firebaseapp.com',
    storageBucket: 'apptarefas-apresetar.firebasestorage.app',
  );
}
