// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaJN_afpZiynO7yARc2jru1ZhuzDC9guo',
    appId: '1:666575782940:web:251f97f599c019c979cbd9',
    messagingSenderId: '666575782940',
    projectId: 'tarefasapp-2025',
    authDomain: 'tarefasapp-2025.firebaseapp.com',
    storageBucket: 'tarefasapp-2025.firebasestorage.app',
    measurementId: 'G-Q1WW4RHLTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5kThjRqGOL2_Pk-4w6PVH0uXx8Oh5UZU',
    appId: '1:666575782940:android:caae82f1f66a8d5979cbd9',
    messagingSenderId: '666575782940',
    projectId: 'tarefasapp-2025',
    storageBucket: 'tarefasapp-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Zki4qxr9loG3Ez2aCEyO7u48zfAK7sE',
    appId: '1:666575782940:ios:e6072ff10556f5b179cbd9',
    messagingSenderId: '666575782940',
    projectId: 'tarefasapp-2025',
    storageBucket: 'tarefasapp-2025.firebasestorage.app',
    iosBundleId: 'com.example.tarefasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Zki4qxr9loG3Ez2aCEyO7u48zfAK7sE',
    appId: '1:666575782940:ios:e6072ff10556f5b179cbd9',
    messagingSenderId: '666575782940',
    projectId: 'tarefasapp-2025',
    storageBucket: 'tarefasapp-2025.firebasestorage.app',
    iosBundleId: 'com.example.tarefasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaJN_afpZiynO7yARc2jru1ZhuzDC9guo',
    appId: '1:666575782940:web:c1240708bb246db379cbd9',
    messagingSenderId: '666575782940',
    projectId: 'tarefasapp-2025',
    authDomain: 'tarefasapp-2025.firebaseapp.com',
    storageBucket: 'tarefasapp-2025.firebasestorage.app',
    measurementId: 'G-HQRGWS0C06',
  );
}
